server:
  port: 6969
spring:
  profiles:
    include: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///G:/My%20Drive/drive_D_on_laptop/file_tai_lieu/Course/waiting_for_job_tasks/software%20engineer_backend/vti_academy/VTI_NOTE/Note_khoa_hoc_chinh/microservice/vti-vmall-project-3/config-server/configs
