server:
  port: 6969
spring:
  profiles:
    include: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///G:/My%20Drive/drive_D_on_laptop/file_with_code/vti-vmall-project-3/config-server/configs
